Fix for update the program.cs file within the Wasm prj
unoplatform/workshops pull request #39
Opened 2019-09-20 19:08 UTC by TomWalkerCodes

Fix for updating the program.cs file within the Wasm project.

2019-09-21 04:43 UTC, michael-hawker requested changes

2019-09-21 04:43 UTC, michael-hawker commented on uno-bootcamp/modules/04-Create-rich-responsive-UIs/README.md
> +[docs-visualboundspadding]: https://github.com/unoplatform/uno/blob/master/src/Uno.UI.Toolkit/VisibleBoundsPadding.md
```suggestion
[docs-visualboundspadding]: https://github.com/unoplatform/uno/blob/master/doc/articles/features/VisibleBoundsPadding.md
```

They just moved this article, so the original link is the correct one.

2019-09-21 04:43 UTC, michael-hawker commented on uno-bootcamp/modules/04-Create-rich-responsive-UIs/README.md
> +By adding the `FeatureConfiguration.UIElement.AssignDOMXamlName = true;` into the program.cs of WebAssembly application (Wasm head), you will see the XAML names directly in the DOM by using the brows
```suggestion
By adding the `FeatureConfiguration.UIElement.AssignDOMXamlName = true;` into the _Program.cs_ file of your WebAssembly application (Wasm head), you will see the XAML names directly in the DOM by using the browser F12 tools.  Make sure to update the name spaces to include `using Uno.UI`;
```

2019-09-24 14:21 UTC, ghuntley commented
Cheers Tom, I don't have write access to your branch so I'll fix the reviewer comments up after merging.

2019-09-24 14:21 UTC, merged